package backend.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Base Data Access Object
 * Provides common database operations
 */
public abstract class BaseDAO {
    protected DatabaseConnection dbConnection;
    
    public BaseDAO() {
        this.dbConnection = DatabaseConnection.getInstance();
    }
    
    /**
     * Get database connection
     * @return Connection object
     * @throws SQLException if not connected
     */
    protected Connection getConnection() throws SQLException {
        return dbConnection.getConnection();
    }
    
    /**
     * Create a PreparedStatement
     * @param sql SQL query with placeholders
     * @return PreparedStatement
     * @throws SQLException if creation fails
     */
    protected PreparedStatement createStatement(String sql) throws SQLException {
        return getConnection().prepareStatement(sql);
    }
    
    /**
     * Create a PreparedStatement with specified options
     * @param sql SQL query with placeholders
     * @param autoGeneratedKeys flag for auto-generated keys
     * @return PreparedStatement
     * @throws SQLException if creation fails
     */
    protected PreparedStatement createStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return getConnection().prepareStatement(sql, autoGeneratedKeys);
    }
    
    /**
     * Execute a query and return ResultSet
     * @param sql SQL query
     * @param params Query parameters
     * @return ResultSet
     * @throws SQLException if execution fails
     */
    protected ResultSet executeQuery(String sql, Object... params) throws SQLException {
        PreparedStatement stmt = createStatement(sql);
        setParameters(stmt, params);
        return stmt.executeQuery();
    }
    
    /**
     * Execute an update/insert/delete statement
     * @param sql SQL statement
     * @param params Statement parameters
     * @return Number of rows affected
     * @throws SQLException if execution fails
     */
    protected int executeUpdate(String sql, Object... params) throws SQLException {
        PreparedStatement stmt = createStatement(sql);
        setParameters(stmt, params);
        return stmt.executeUpdate();
    }
    
    /**
     * Execute an update and return generated key
     * @param sql SQL statement
     * @param params Statement parameters
     * @return Generated key, or -1 if failed
     * @throws SQLException if execution fails
     */
    protected long executeUpdateWithKey(String sql, Object... params) throws SQLException {
        PreparedStatement stmt = createStatement(sql, Statement.RETURN_GENERATED_KEYS);
        setParameters(stmt, params);
        int affectedRows = stmt.executeUpdate();
        
        if (affectedRows == 0) {
            return -1;
        }
        
        try (ResultSet rs = stmt.getGeneratedKeys()) {
            if (rs.next()) {
                return rs.getLong(1);
            }
        }
        
        return -1;
    }
    
    /**
     * Set parameters in PreparedStatement
     * @param stmt PreparedStatement
     * @param params Parameters to set
     * @throws SQLException if setting fails
     */
    protected void setParameters(PreparedStatement stmt, Object... params) throws SQLException {
        if (params != null) {
            for (int i = 0; i < params.length; i++) {
                stmt.setObject(i + 1, params[i]);
            }
        }
    }
    
    /**
     * Close resources safely
     * @param rs ResultSet to close
     * @param stmt Statement to close
     */
    protected void closeResources(ResultSet rs, Statement stmt) {
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                System.err.println("Error closing ResultSet: " + e.getMessage());
            }
        }
        
        if (stmt != null) {
            try {
                stmt.close();
            } catch (SQLException e) {
                System.err.println("Error closing Statement: " + e.getMessage());
            }
        }
    }
    
    /**
     * Close resources safely (Statement only)
     * @param stmt Statement to close
     */
    protected void closeResources(Statement stmt) {
        closeResources(null, stmt);
    }
}
